name: Deploy to ECR
on:
  push:
    branches: [ main, "dev" ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: llatan-microservice
        IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
  deploy:
    needs: build
    name: deploy Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ secrets.HOST }}
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.KEY }}
    - name: run ssh
      env:
        DOCKER_IMAGE_NAME: llatan-microservice
      run: |
          ssh staging docker stop "$DOCKER_IMAGE_NAME" || true
          ssh staging docker rm "$DOCKER_IMAGE_NAME" || true
          ssh staging docker rmi -f $(ssh staging docker images | grep "$DOCKER_IMAGE_NAME" | awk "{print \$3}")  || true
          ssh staging docker pull "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          ssh staging docker run  --name $DOCKER_IMAGE_NAME -p $PORT:8080 -d "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"